version: "3.9"

x-mongodb-host: &MONGODB_HOST
  mongodb
x-mongodb-user: &MONGODB_USER
  admin
x-mongodb-password: &MONGODB_PASSWORD
  password
x-mongodb-port: &MONGODB_PORT
  27017
x-mongodb-db: &MONGODB_DB
  app
x-redis-host: &REDIS_HOST
  redis
x-redis-port: &REDIS_PORT
  6379

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    hostname: *MONGODB_HOST
    ports:
      - target: *MONGODB_PORT
        published: 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: *MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: *MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: *MONGODB_DB
    volumes:
      - mongo-data:/data/db
      - mongo-cfg:/data/configdb

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: *MONGODB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: *MONGODB_PASSWORD
      ME_CONFIG_MONGODB_SERVER: *MONGODB_HOST

  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: *REDIS_HOST
    ports:
      - target: *REDIS_PORT
        published: 6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app:rw
      - app-root:/root:rw
    working_dir: /app
    environment:
      APP_MONGODB_USER: *MONGODB_USER
      APP_MONGODB_PASSWORD: *MONGODB_PASSWORD
      APP_MONGODB_HOST: *MONGODB_HOST
      APP_MONGODB_PORT: *MONGODB_PORT
      APP_REDIS_HOST: *REDIS_HOST
      APP_REDIS_PORT: *REDIS_PORT

volumes:
  mongo-data:
    name: mongo-data
    driver: local
  mongo-cfg:
    name: mongo-cfg
    driver: local
  app-root:
    name: app-root
    driver: local
